### ISSUE TITLE
Time source specific properties should be self-contained

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#173]
As a developer, I'd like to refactor `time-source` application, so it doesn't use the `dateFormat` property from `TriggerProperties`. This is specific to `time-source`; hence, it needs to be self-contained.

**Acceptance:**
~~-`time-source` does not rely on `TriggerProperties`~~
- `dateFormat` is time-source specific property and it should be self-contained

**Comment by markfisher** [comment]
The time source *should* rely on `TriggerProperties`. In fact, most of the configurable properties for it ARE related to the Trigger (cron, delay, etc). However, the "dateFormat" property itself should not be associated with the Trigger. The date format is specific to the Time source itself; when it is triggered it emits a Message with that date format determining the payload String. Other apps that rely on generic Trigger capabilities will do different things.

**Comment by ericbottard** [comment]
Turns out the `dateFormat` *is* used by the simple trigger, for *parsing* a date when using the `date` mode.
See https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/ae64ebad9450680fa8762d045ad5ff25989cdefa/app-starters-common/app-starters-trigger-common/src/main/java/org/springframework/cloud/stream/app/trigger/TriggerConfiguration.java#L73 and https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/ae64ebad9450680fa8762d045ad5ff25989cdefa/app-starters-common/app-starters-trigger-one-common/src/main/java/org/springframework/cloud/stream/app/trigger/TriggerPropertiesMaxMessagesDefaultOne.java#L118

**Comment by markfisher** [comment]
That's technically a different purpose, and it seems wrong to reuse that property for the *display* format. Given that this is not a generally useful app, we can probably let it slide though.

Also, shouldn't it be possible to use `Date` instead of `String` in the `@ConfigurationProperties` to rely on the underlying conversion support anyways? (thus not needing a format property at that level)

**Comment by ericbottard** [comment]
> That's technically a different purpose, and it seems wrong to reuse that property for the display format. 
I agree...

> Also, shouldn't it be possible to use Date instead of String
Definitely should be, I guess we wanted full flexibility (which makes less sense here than say ... when using dates in the `aggregate-counter` for example). Also, not sure which default would be used, and if it would be Locale specific..

**Comment by ericbottard** [comment]
Closing as we marked as wontfix
