### ISSUE TITLE
tasklaunchrequest-transform-processor is skipping payload/message

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#269]
As a user, I'm using `tasklaunchrequest-transform-processor` in SCDF and while testing it, I'm unable to receive the payload from an upstream application wrapped in the `TaskLaunchRequest`. It looks like the [inbound message](https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/processor/spring-cloud-starter-stream-processor-tasklaunchrequest-transform/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/transform/processor/TasklaunchrequestTransformProcessorConfiguration.java#L61) is not populated in the request object [_sample [application](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-samples/taskprocessor/src/main/java/io/spring/TaskProcessor.java#L59) used to_].

Currently, there isn't any other way to the receive upstream event/payload info at the launched Task level. 

This issue is will be moved to the new repo eventually.

**Comment by cppwfs** [comment]
The ability to pass a payload as an attribute of the TaskLaunchRequest was removed because the TaskLauncherSInk has no way to pass this along to the Deployer's TaskLauncher.   Unless we  assume the payload is a string and store it as a property or a command line argument.   While this is possible we have no way of handling non-text payloads i.e. Objects unless we serialize them as something like JSON.   This is a part of the discussion where we need to look at a solution beyond the use of the Deployer for the TaskLauncher sink.   Thoughts?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud-stream-app-starters/app-starters-release#46
