### ISSUE TITLE
httpclient.processor: additional variable(s) on SpEL context to evaluate reply

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-stream-app-starters#274]
Please expose the  original `message` in evaluation context while evaluating the final replay in`httpclient.processor`, so the `replyExpression` could be written like this :
 ````
{
'name':#message.payload.someExpression,
'val': body.anotherExpression
}
````

Thanks

**Comment by artembilan** [comment]
This looks like a new feature request.
Since all the SCSt applications have been severed to their own repositories, consider to move the issue to the appropriate place https://github.com/spring-cloud-stream-app-starters/httpclient/issues.

And, please, share more info what is the purpose of the feature.

Thanks

**Comment by jvmlet** [comment]
> And, please, share more info what is the purpose of the feature.
Well, with the current implementation I can only transform message against response body, the original message payload is not accessible in `replyExpression`. 
The purpose of the feature is  to expose original message payload in evaluation context and provide capability to include some values from original message to transformed message.

**Comment by artembilan** [comment]
OK. But I said you already: this is already a wrong place to ask such a new feature.

Plus keep in mind that nowhere in Spring Integration we have something like `replyExpression`.
The standard behavior is to return the `reply` as is and let the further component to deal with its transformation. It isn't the tarter service gateway responsibility to modify reply. That doesn't look like loosely coupling and microservices architecture. 

Therefore you should just place the `requestMessage` into headers before `httpclient` and use it afterwards in the `transformer`. 

OTOH that isn't good idea to expose it as a SpEL variable because we would have to create `EvaluattionContext` for each message to send. That is some performance impact for most cases when we don't need `requestMessage` for reply evaluation. Therefore I'd recommend to do such a logic only in your custom `httpclient`, but not as an out-of-the-box requirement. Anyway that's why they are called `starters`: you pick up the one as is and modify for your business. That is the best middle ground to avoid unexpected misbehavior in other places.

Does it make sense for you?

**Comment by jvmlet** [comment]
Sounds reasonable... 
I can't find the example how to customize the standard starter, I would appreciate  if you point me to some sample.
Thanks
Alexander

**Comment by artembilan** [comment]
Looks like this should help you somehow: http://docs.spring.io/spring-cloud-stream-app-starters/docs/1.0.4.RELEASE/reference/html/_introduction.html#_patching_pre_built_applications

**Comment by jvmlet** [comment]
Yeah,  I saw this, but it doesn't show how to customize the processor...

**Comment by artembilan** [comment]
Eh... Agreed. That is embarrassing without copy/paste of that code :smile: 

Consider the [Aggregation](http://docs.spring.io/spring-cloud-stream/docs/1.0.3.RELEASE/reference/htmlsingle/index.html#_aggregation) approach for your solution.

So, you can have a `header-enricher` processor before `httpclient`, then `httpclient`, and `transformer` afterwards to consult the `reply` as a `payload` and `headers` for request message.

Hope that helps

**Comment by jvmlet** [comment]
@artembilan, I've tried  what you'd suggested, but got `MessageHeaders is immutable` :

![image](https://cloud.githubusercontent.com/assets/6664858/20298040/7e236530-ab1c-11e6-8243-afa8660e6394.png)
This is how I tried to  enrich headers with `transformer` starter:
`transformer.expression=null == headers.put('myHeader','myValue')?payload:payload`

Please advise 
Thanks

**Comment by artembilan** [comment]
@jvmlet ,

Eh... I agree that there is no out-of-the-box `header-enricher-processor`. Maybe just because there was no request before?..

You can achieve that withe the custom `processor` configuration for your `Aggregation`:
````java
@EnableBinding(Processor.class)
public class HeaderEnricherConfiguration {

        @Bean
	public IntegrationFlow headerEnricherFlow() {
                return IntegrationFlows.from(Processor.INPUT)
					.enrichHeaders(e -> e.headerFunction("requestMessage", m -> m))
					.channel(Processor.OUTPUT)
					.get();
	}

}
````

Right, this isn't flexible, but we really talk here about your custom solution. So, such a hard code should fix your current requirements.

Regarding mutability of `MessageHeaders`. Right, that is a fact. You can't modify headers directly you have to crate a new `Message` using `MessageBuilder`. Maybe something like this:
```
transformer.expression=T(org.springframework.integration.support.MessageBuilder).fromMessage(#root).setHeader('requestMessage',#root).build()
```

**Comment by jvmlet** [comment]
Thanks, the above `transformer.expression` does the trick.
