### ISSUE TITLE
Building project without .settings.xml breaks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-app-starters#83]
_From @pberman-pivotal on March 18, 2016 18:38_

Hello, 
I was following the instructions for  the quickstart, and spent 3 hours wondering why 
mvn clean package 

kept failing, then a colleague told me about the .settings.xml file. I ran 

mvn clean package -s .settings.xml

And was good to go. I think it would be helpful to mention this in the quick start, the existence of this system file.

_Copied from original issue: spring-cloud/spring-cloud-stream-modules#231_

**Comment by sobychacko** [comment]
I don't think this issue exists any longer in the app starters repository as the root level pom.xml contains information about all the necessary repositories. The issue was happening when using `mvn clean package` and it is fixed for this command. However, the recommended approach is to always build using the provided maven wrapper script `./mvnw`. This is mentioned in the README for the app starters repository.
