### ISSUE TITLE
In the generated application rely on the default @SpringBootApplication scanBasePackages

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-app-starters#96]
Since we develop here micro-services, that should not be secret that one `main` class just with `@SpringBootApplication` does the entire trick around the target protocol-specific adapter (service). 
Typically it is just a single `@Configuration` class.

I don't see reason to add extra `@Import`  in the generated `main` class, since we can just move the last one to the application package and rely on the `@ComponentScan`. Fully similar like we do in the apps tests.
It doesn't matter that we generate applications for different binders, we will use only one at runtime. So, the generate jar must have `@SpringBootApplication` on the top-level package to be able to pick up the app configs automatically without any extra manipulations for the generator config.
Plus we will be free with naming for app `@Configuration`s.

Let me know what I have missed here around that led you to follow with the `@Import` solution.

**Comment by sobychacko** [comment]
@artembilan Initially we were using the auto configuration approach by providing spring.factories in all the starters. This turned out to be an issue for some applications as it would automatically bring in configuration thats not needed or give conflicts. We had to manually exclude those beans. To fix this issue, we disabled auto configuration completely in the starters and manually inject the `@Import` annotation in the generated application main class using the plugin. This way, the application won't get auto configured with the beans, but only if we provide the necessary import. 

The above works using the plugin, but when we use [start-scsapps](http://start-scs.cfapps.io/) for the same purpose, the users have to manually modify the main class to add that `@Import`. 

Using `@SpringBootApplication` and making the application main class reside in the same package name as the `@Configuration` class has few issues as well. 

- The issues mentioned above would be manifested here again, i.e. since `@SpringBootApplication` does a component scan on the base package, it would do an auto configuration for the beans thus having the same problems as above.

- We cannot really force the use of the same package used for `@Configuration` for the end user applications due to organizational restrictions and other reasons. If someone changes the package to a different one than whats used for the configuration, then using `@SpringBootApplication` for auto configuration won't work anyway since we don't provide spring.factories in the starters. 

cc @markfisher - there were some issues we had with auto configuration which made us to switch to @Import.

**Comment by markfisher** [comment]
The specific conflict we encountered was when building upon one of the starters as a library by embedding it and adding additional logic (e.g. transformation). In such a case, we don't want the binding to happen for the embedded app, but rather only for the composed app that includes that embedded app alongside additional functionality.

**Comment by artembilan** [comment]
Thank you, guys, for feedback.
I didn't think about the Initializr when raised this issue and now I think that for global my concern doesn't matter, just because the generated app (via Initializr) may have any package for the top-level `main` with `@SpringBootApplication`.
My point was about out-of-the-box apps, when I have some naming restrictions for my app `@Configuration` class and should do some other steps to let generator to know about my classes. And not just rely on the built-in `@ComponentScan` from the `@SpringBootApplication` in the top-level package. Current `kafka/rabbit` structure eliminates that trick from Boot.
OK. Now have more info around I can live with these restrictions.

But on the other hand here are my additional five cents.

I don't understand the fear against auto-configuration. Just because all others are there anyway. For example I was surprised that SC-AWS auto-configure for me SES service when I need only S3. 
That is a different story: nevermind :smile: 
But from other side my main goal of the `s3-source` micro-service hasn't been reached. Just because my `AmazonS3SourceConfiguration` isn't visible by `SpringApplication`!
That's why I would like to see `S3SourceRabbitApplication` in the `org.springframework.cloud.stream.app.s3.source` package, not `rabbit` sub-package to let OOTB app to be as clear micro-service.

Backing to the auto-configuration fear, I'd say that something wrong and weird here around with the auto-configuration concepts, like it is in the Spring Boot. If you worry about some customization from the end-user application, you should apply to your autoconfigs all those possible useful `@Conditional` and really let end-user to rely on just the auto-configuration and override those beans which he needs. E.g. with the same S3 Source I would like to leave the `S3InboundFileSynchronizer` bean as is, but add `localFilter` to the `S3InboundFileSynchronizingMessageSource` bean overriding it. Right, the `localFilter` isn't supported in the `AbstractRemoteFileSourceProperties`.
Having the current state, I don't see how those OOTB `@Configuration`s can be useful for custom app, independently of the fact of `@ComponentScan` or `@Import`.

Again I may miss something, so forgive me for ignorance. For this purpose I would like to see the code of that composed application, because it isn't clear for me how `@EnableBinding` can be skipped for the "embedded app".

**Comment by sobychacko** [comment]
For a custom app, @Configuration would only be useful if they import that configuration class using @Import. 

By embedded app, I think Mark was referring to an aggregated app. In SCS, for aggregated apps, there is no binding takes place even if there is a binder on the class path. For instance, if I have an aggregated app like this - `http | processor | gemfire` (all bundled into a single app), there won't be any binding even if the backing http implementation is http-source-kafka.

**Comment by mbogoevici** [comment]
`@EnableBinding` is not skipped for an embedded app, it is just that in the specific case when the aggregated chain begins with a source and ends with a sink, no channels will be bound (because all are directly bound between the applications). If the aggregated chain starts or ends with a processor, the starting input channel or ending output channel will be bound. Unfortunately, even if no channel is supposed to be bound, we do require the presence of a binder (which, by itself, is a bug).

Generally speaking, the issue with autoconfiguration here is that it prevents the libraries to be reused in a 'simple' fashion - e.g. only using the repositories in the analytics module Also, in aggregation scenarios we will not want the modules to be auto-imported at the root level, as aggregation relies on creating child contexts for each aggregated application (also for being able to set up configuration properties separately and to order them explicitly in the sequence).

**Comment by sabbyanandan** [comment]
The binder is not included in the aggregate applications anymore. @artembilan - if you've any specific issue that you'd like to bring up, please create a separate ticket in the [release-train](https://github.com/spring-cloud-stream-app-starters/app-starters-release) repo.
